### ISSUE TITLE
Main?

### ISSUE THREAD

**Issue by mitchellshreiner** [jonatanolofsson/mht#2]
I have recently gotten the program to build, I think, but do not know where to start for using the program. What is the design flow of this project? How does one test it? 

Also, my assumption that it was built is purely on the event of getting pybind11, Eigen, and tup installed and running tup command in the top directory. This resulted in compiling murty and outputting a compiled library file. But then what do I do?

**Comment by jonatanolofsson** [comment]
Have a look at the [tests](https://github.com/jonatanolofsson/mht/blob/master/tests/test_mht.py)
