### ISSUE TITLE
no module named murty.murty

### ISSUE THREAD

**Issue by zl930216** [jonatanolofsson/mht#3]
I tried to run the program in tests directory after "python setup.py build" was executed， but always got the error showing that "no module named murty.murty". May I ask how to fix this problem?

**Comment by jonatanolofsson** [comment]
Hi there,

Admittedly, the README isn't quite what it should be yet, but I updated it for you just now!

Have a look

**Comment by ikki75** [comment]
Hello. Thank you for this wonderful work!
I have downloaded it and try to run the crosstrack.png.py script, I get the same error:
   ```
 from .murty import Murty
ModuleNotFoundError: No module named 'murty.murty'
```
I don't know what I have not done well. 
Could you help me please?

Thank you veru much

**Comment by sriharibr** [comment]
I installed tup and executed it in root directory (RHEL) : 

[root@localhost tup]# ./tup 
[ tup ] [0.000s] Scanning filesystem...
[ tup ] [0.107s] Reading in new environment variables...
[ tup ] [0.107s] Parsing Tupfiles...
 1) [0.004s] mht
 0) [0.002s] mht/murty                                                                                                                     
 [  ] 100%
[ tup ] [0.128s] No files to delete.                                                                                                       
[ tup ] [0.128s] Generating .gitignore files...
[ tup ] [0.232s] Executing Commands...
 0) [27.507s] mht/murty: clang++ -Qunused-arguments -std=c++17 -Wall -Werror -Wno-unknown-pragmas -Wfatal-errors -pedantic-errors -Wextra -Wcast-align -O3 -fPIC -isystem/usr/include/eigen3  -shared -I../deps/pybind11/include -I/usr/local/include/python3.7m -I/usr/local/include/python3.7m -Wno-nested-anon-types  -Wno-unused-result -Wsign-compare -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes murty.cpp -o murty.cpython-37m-x86_64-linux-gnu.so   
 [ ] 100%
[ tup ] [27.828s] Updated.                                                                                                                 
[root@localhost tup]# 


Then built & installed python3.7 module : 
[root@localhost mht]# python3.7 setup.py build
running build
running build_py
[root@localhost mht]# python3.7 setup.py install
running install
running bdist_egg
running egg_info
writing mht.egg-info/PKG-INFO
writing dependency_links to mht.egg-info/dependency_links.txt
writing top-level names to mht.egg-info/top_level.txt
reading manifest file 'mht.egg-info/SOURCES.txt'
writing manifest file 'mht.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/__init__.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/cluster.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/clusterhyp.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/hypgen.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/kf.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/mht.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/models.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/plot.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/sensors.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/target.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/track.py -> build/bdist.linux-x86_64/egg/mht
copying build/lib/mht/utils.py -> build/bdist.linux-x86_64/egg/mht
creating build/bdist.linux-x86_64/egg/murty
copying build/lib/murty/__init__.py -> build/bdist.linux-x86_64/egg/murty
byte-compiling build/bdist.linux-x86_64/egg/mht/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/cluster.py to cluster.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/clusterhyp.py to clusterhyp.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/hypgen.py to hypgen.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/kf.py to kf.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/mht.py to mht.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/models.py to models.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/plot.py to plot.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/sensors.py to sensors.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/target.py to target.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/track.py to track.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/mht/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/murty/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying mht.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mht.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mht.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mht.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/mht-1.0.0-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mht-1.0.0-py3.7.egg
Removing /usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg
Copying mht-1.0.0-py3.7.egg to /usr/local/lib/python3.7/site-packages
mht 1.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg
Processing dependencies for mht==1.0.0
Finished processing dependencies for mht==1.0.0



Yet , i'm getting  the error  "no module named murty.murty" 

[root@localhost mht]# cd tests/
[root@localhost tests]# python3.7 test_mht.py 
Traceback (most recent call last):
  File "test_mht.py", line 24, in <module>
    import mht
  File "/usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg/mht/__init__.py", line 18, in <module>
  File "/usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg/mht/mht.py", line 23, in <module>
  File "/usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg/mht/cluster.py", line 28, in <module>
  File "/usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg/mht/hypgen.py", line 20, in <module>
  File "/usr/local/lib/python3.7/site-packages/mht-1.0.0-py3.7.egg/murty/__init__.py", line 1, in <module>
**ModuleNotFoundError: No module named 'murty.murty'**

 Kindly help fix this problem?
